from __future__ import annotations

from typing import Any, Protocol


class SchedulerRepository(Protocol):
    async def save_job_definition(self, job_id: str, value: dict[str, Any]) -> None: ...
    async def load_job_definitions(self) -> tuple[dict[str, Any], ...]: ...
    async def save_job_state(self, job_id: str, value: dict[str, Any]) -> None: ...
    async def load_job_state(self, job_id: str) -> dict[str, Any] | None: ...
    async def append_execution_history(self, value: dict[str, Any]) -> None: ...
    async def query_execution_history(self, job_id: str | None = None) -> tuple[dict[str, Any], ...]: ...
    async def delete_job_persistence(self, job_id: str) -> None: ...
