from __future__ import annotations

from typing import Any, Protocol

from .models import StateEntry, StateKey, StateSnapshot


class StateRepository(Protocol):
    async def set(self, state_key: StateKey, value: Any, **kwargs: Any) -> StateEntry: ...
    async def get(self, state_key: StateKey, **kwargs: Any) -> StateEntry | None: ...
    async def update(self, state_key: StateKey, updater: Any, **kwargs: Any) -> StateEntry: ...
    async def compare_and_set(self, state_key: StateKey, expected_value: Any, new_value: Any, **kwargs: Any) -> StateEntry | None: ...
    async def delete(self, state_key: StateKey, **kwargs: Any) -> StateEntry | None: ...
    async def list_namespace(self, namespace: str, **kwargs: Any) -> tuple[StateEntry, ...]: ...
    async def snapshot(self, namespace: str | None = None, **kwargs: Any) -> StateSnapshot: ...
    async def restore(self, snapshot: StateSnapshot, **kwargs: Any) -> None: ...
    async def purge_expired(self) -> int: ...
