const state={results:[],selected:null};
const $=(selector)=>document.querySelector(selector);
const escapeHtml=(value)=>String(value).replace(/[&<>'"]/g,character=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"})[character]);
const money=(value)=>value!==null&&value!==undefined&&value!==""&&Number.isFinite(Number(value))?`$${Number(value).toLocaleString(undefined,{maximumFractionDigits:2})}`:"—";
const text=(value,fallback="—")=>escapeHtml(value===null||value===undefined||value===""?fallback:value);
const signalClass=(decision)=>decision==="BUY_WATCH"?"buy":decision==="SELL_WATCH"?"sell":"no";
const remaining=(seconds)=>{const value=Math.max(0,Number(seconds)||0);if(value<60)return value>0?"<1 min":"Expired";return `${Math.ceil(value/60)} min`;};

async function getJson(url){const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),32000);try{const response=await fetch(url,{headers:{Accept:"application/json"},cache:"no-store",signal:controller.signal});const payload=await response.json();if(!response.ok)throw new Error(payload.reason||payload.status||`HTTP ${response.status}`);return payload;}finally{clearTimeout(timer);}}

async function loadScanner(){const status=$("#scannerStatus");status.textContent="Refreshing Alpaca, FlashAlpha, Quiver and Finnhub evidence…";try{const payload=await getJson("/api/stocks/scanner");state.results=payload.results||[];status.textContent=`${state.results.length} symbols analysed · scanner refresh does not extend setup validity`;renderScanner();}catch(error){status.textContent=`Scanner unavailable: ${error.message}`;status.classList.add("error");}}

function filteredResults(){const signal=$("#signalFilter").value;const validity=$("#validityFilter").value;const timeframe=$("#timeframeFilter").value;return state.results.filter(item=>(signal==="ALL"||item.decision===signal)&&(validity==="ALL"||item.setup_state===validity)&&(timeframe==="ALL"||item.trigger_timeframe===timeframe||item.analysis_timeframe===timeframe));}
function renderScanner(){const rows=$("#scannerRows");rows.innerHTML=filteredResults().map(item=>{const flash=item.additional_context?.flashalpha||{};const active=item.setup_state==="ACTIVE";return `<tr data-symbol="${text(item.asset)}"><td><strong>${text(item.asset)}</strong><br><small>${text(item.company_name,"")}</small></td><td><span class="signal ${signalClass(item.decision)}">${text(item.decision).replaceAll("_"," ")}</span></td><td>${text(item.trigger_timeframe)} · ${text(item.setup_state)}</td><td>${money(item.current_price)} / ${money(item.entry)}</td><td>${money(item.stop_loss)} → ${money(item.target)}<br><small>${item.reward_risk?`${text(item.reward_risk)}:1 R:R`:"No active levels"}</small></td><td>${text(flash.net_gex_label)}<br><small>Flip ${money(flash.gamma_flip)}</small></td><td class="state-${String(item.setup_state||"").toLowerCase()}">${active?remaining(item.validity_remaining_seconds):text(item.expiry_reason,item.setup_state)}</td><td>${text(item.reason_code)}</td></tr>`;}).join("")||'<tr><td colspan="8">No scanner results match these filters.</td></tr>';rows.querySelectorAll("tr[data-symbol]").forEach(row=>row.addEventListener("click",()=>analyse(row.dataset.symbol)));}

async function analyse(symbol){const panel=$("#analysisPanel");panel.innerHTML=`<div class="empty-state"><p class="eyebrow">${text(symbol)}</p><h2>Building multi-provider analysis…</h2><p>Validating price structure, positioning, alternative data and freshness.</p></div>`;panel.scrollIntoView({behavior:"smooth",block:"start"});try{const payload=await getJson(`/api/stocks/${encodeURIComponent(symbol)}/analysis`);state.selected=payload;renderAnalysis(payload);}catch(error){panel.innerHTML=`<div class="empty-state"><p class="eyebrow">Analysis unavailable</p><h2>${text(symbol)}</h2><p class="error">${text(error.message)}</p></div>`;}}

function renderAnalysis(payload){const a=payload.analysis||{};const flash=a.additional_context?.flashalpha||{};const inactive=a.setup_state!=="ACTIVE";$("#analysisPanel").innerHTML=`<div class="analysis-head"><div><p class="eyebrow">${text(payload.company_name)}</p><h2>${text(payload.symbol)}</h2><p>${text(a.reason_code)} · ${text(a.analysis_timeframe)} structure / ${text(a.trigger_timeframe)} trigger</p></div><div class="decision-card"><span>Current decision</span><strong class="signal ${signalClass(a.decision)}">${text(a.decision).replaceAll("_"," ")}</strong><p class="state-${String(a.setup_state||"").toLowerCase()}">${text(a.setup_state)} · ${a.setup_state==="ACTIVE"?remaining(a.validity_remaining_seconds):text(a.expiry_reason,"fresh analysis required")}</p></div></div><div class="metric-grid ${inactive?"expired-levels":""}"><article class="metric"><span>Current / entry</span><strong>${money(a.current_price)} / ${money(a.entry)}</strong></article><article class="metric"><span>Stop</span><strong>${money(a.stop_loss)}</strong></article><article class="metric"><span>Target</span><strong>${money(a.target)}</strong></article><article class="metric"><span>Reward:risk</span><strong>${a.reward_risk?`${text(a.reward_risk)}:1`:"—"}</strong></article></div><div class="metric-grid"><article class="metric"><span>Generated</span><strong>${formatTime(a.analysis_generated_at)}</strong></article><article class="metric"><span>Market data as of</span><strong>${formatTime(a.market_data_as_of)}</strong></article><article class="metric"><span>Valid until</span><strong>${formatTime(a.setup_expires_at)}</strong></article><article class="metric"><span>Last confirmed close</span><strong>${formatTime(a.last_confirmed_candle_close)}</strong></article></div><div class="provider-detail"><article><h3>FlashAlpha</h3><p>Regime: ${text(flash.net_gex_label)}</p><p>Gamma flip: ${money(flash.gamma_flip)}</p><p>Call wall: ${money(flash.call_wall)} · Put wall: ${money(flash.put_wall)}</p><p>As of: ${formatTime(flash.as_of)}</p></article><article><h3>Quiver</h3><p>Score: ${text(a.score)} / threshold ${text(a.score_threshold)}</p><p>${(a.reasons||[]).map(item=>text(item)).join(" · ")||"No supportive activity returned."}</p><p>${(a.cautions||[]).map(item=>text(item)).join(" · ")||"No additional cautions."}</p></article><article><h3>Finnhub + Alpaca</h3><p>Finnhub quote: ${money(a.additional_context?.quote)}</p><p>Recent news: ${text(a.additional_context?.news_count,0)}</p><p>Quote divergence: ${text(a.additional_context?.alpaca_quote_divergence_pct)}%</p><p>Execution: disabled</p></article></div>`;}
function formatTime(value){if(!value)return"—";const date=new Date(value);return Number.isNaN(date.getTime())?"—":date.toLocaleString([],{month:"short",day:"numeric",hour:"2-digit",minute:"2-digit",timeZoneName:"short"});}

let searchTimer;$("#stockSearch").addEventListener("input",event=>{clearTimeout(searchTimer);const q=event.target.value.trim();if(!q){$("#searchResults").innerHTML="";return;}searchTimer=setTimeout(async()=>{try{const payload=await getJson(`/api/stocks/search?q=${encodeURIComponent(q)}`);$("#searchResults").innerHTML=(payload.results||[]).map(item=>`<button type="button" data-symbol="${text(item.symbol)}"><strong>${text(item.symbol)}</strong><span>${text(item.name)}</span></button>`).join("");$("#searchResults").querySelectorAll("button").forEach(button=>button.addEventListener("click",()=>{ $("#stockSearch").value=button.dataset.symbol;$("#searchResults").innerHTML="";analyse(button.dataset.symbol);}));}catch(error){$("#searchResults").textContent=error.message;}},180);});
$("#stockSearchForm").addEventListener("submit",event=>{event.preventDefault();const symbol=$("#stockSearch").value.trim().toUpperCase();if(symbol)analyse(symbol);});
$("#refreshScanner").addEventListener("click",loadScanner);["#signalFilter","#validityFilter","#timeframeFilter"].forEach(selector=>$(selector).addEventListener("change",renderScanner));
function tickSetup(item){if(!item||item.setup_state!=="ACTIVE")return;if(item.setup_expires_at){item.validity_remaining_seconds=Math.max(0,Math.floor((new Date(item.setup_expires_at).getTime()-Date.now())/1000));}else{item.validity_remaining_seconds=Math.max(0,(Number(item.validity_remaining_seconds)||0)-1);}if(item.validity_remaining_seconds===0)Object.assign(item,{setup_state:"EXPIRED",expiry_reason:"SETUP_EXPIRED",decision:"NO_TRADE",reason_code:"SETUP_EXPIRED",setup_status:"expired",entry:null,stop_loss:null,target:null,reward_risk:null});}
setInterval(()=>{state.results.forEach(tickSetup);renderScanner();if(state.selected?.analysis){tickSetup(state.selected.analysis);renderAnalysis(state.selected);}},1000);
setInterval(loadScanner,120000);
loadScanner();
