from __future__ import annotations

from typing import Any, Protocol

from .models import AuditQuery, AuditRecord, AuditSnapshot


class AuditRepository(Protocol):
    async def append(self, **kwargs: Any) -> AuditRecord: ...
    async def get(self, record_id: str) -> AuditRecord | None: ...
    async def query(self, query: AuditQuery) -> tuple[AuditRecord, ...]: ...
    async def verify_integrity(self) -> tuple[str, ...]: ...
    async def snapshot(self) -> AuditSnapshot: ...
    async def count(self) -> int: ...
